apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ printf "%s-%s-%s-%s" "letsencrypt" .Values.app.env "emote-chat" "client" }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: t@zigah.co
    privateKeySecretRef:
      name: {{ printf "%s-%s-%s-%s" "letsencrypt" .Values.app.env "emote-chat" "client" }}
    solvers:
      - http01:
          ingress:
            class: nginx
